# Generated by Django 2.1 on 2018-08-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='album_title',
        ),
    ]
